apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: migration
value: 200
globalDefault: false
description: "This priority class should be used for migration pods only"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal
value: 100
globalDefault: false
description: "This priority class should be used for normal pods only"
