pgadmin4:
  ingress:
    enabled: true
    hosts:
      - host: localhost
        paths:
        - pathType: Prefix
          path: "/"
postgresql:
  postgresqlPassword: postgres
kubeview:
  ingress:
    enabled: true