pgadmin4:
  ingress:
    enabled: true
    hosts:
      - host: localhost
        paths:
        - pathType: Prefix
          path: "/"

postgresql:
  postgresqlPassword: postgres
  postgresqlDatabase: noxudb
  primary:
    priorityClassName: db

kratos:
  kratos:
    autoMigrate: true
    development: true
    ingress:
      public:
        enabled: true
      admin:
        enabled: true
    config:
      dsn: postgres://postgres:postgres@noxucloud-postgresql:5432/noxudb?sslmode=disable&max_conns=20&max_idle_conns=4
      secrets:
        session:
          - dolore occaecat nostrud Ut
          - sit et commodoaute ut voluptate consectetur Duis

oathkeeper:
  ingress:
    proxy:
      enabled: true
    api:
      enabled: true
  oathkeeper:
    accessRules: |
      - id: "ory:kratos:public"
        upstream:
          preserve_host: true
          url: "http://kratos:4433"
          strip_path: /.ory/kratos/public
        match:
          url: $BASE_URL/.ory/kratos/public/<**>"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
        authenticators:
          - handler: noop
        authorizer:
          handler: allow
        mutators:
          - handler: noop
      - id: "ory:kratos-selfservice-ui-node:anonymous"
        upstream:
          preserve_host: true
          url: "http://kratos-selfservice-ui-node:4435"
        match:
          url: $BASE_URL/<{error,recovery,verify,auth/*,**.css,**.js}{/,}>"
          methods:
            - GET
        authenticators:
          - handler: anonymous
        authorizer:
          handler: allow
        mutators:
          - handler: noop
      - id: "ory:kratos-selfservice-ui-node:protected"
        upstream:
          preserve_host: true
          url: "http://kratos-selfservice-ui-node:4435"
        match:
          url: $BASE_URL/<{,debug,dashboard,settings}>"
          methods:
            - GET
        authenticators:
          - handler: cookie_session
        authorizer:
          handler: allow
        mutators:
          - handler: id_token
        errors:
          - handler: redirect
            config:
              to: $BASE_URL/auth/login
      - id: "noxunote:mynotesapi:public"
        upstream:
          preserve_host: true
          url: "http://mynotesapi:2268"
        match:
          url: $BASE_URL/<{mynotes}>"
          methods:
            - GET
        authenticators:
          - handler: anonymous
        authorizer:
          handler: allow
        mutators:
          - handler: noop
      
      - id: "noxunote:mynotesapi:protected"
        upstream:
          preserve_host: true
          url: "http://mynotesapi:2268"
        match:
          url: $BASE_URL/mynotes/<{account,notes,notes/*}>"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
        authenticators:
          - handler: cookie_session
        authorizer:
          handler: allow
        mutators:
          - handler: id_token
          - handler: header
        errors:
          - handler: redirect
            config:
              to: $BASE_URL/auth/login
      - id: "myheavyfiles:myheavyfilesapi:protected"
        upstream:
          preserve_host: true
          url: "http://myheavyfilesapi:2267"
        match:
          url: $BASE_URL/documents/<{,*}>"
          methods:
            - GET
            - POST
            - DELETE
        authenticators:
          - handler: cookie_session
        authorizer:
          handler: allow
        mutators:
          - handler: id_token
          - handler: header
        errors:
          - handler: redirect
            config:
              to: $BASE_URL/auth/login
    config:
      log:
        level: warning
        format: json
      serve:
        proxy:
          cors:
            enabled: true
            allowed_origins:
              - "http://127.0.0.1:4200"
              - "https://*.noxunote.fr"
            allowed_methods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
            allowed_headers:
              - Authorization
              - Content-Type
            exposed_headers:
              - Content-Type
            allow_credentials: true
            debug: true
      errors:
        fallback:
          - json
        handlers:
          redirect:
            config:
              to: $BASE_URL
              when:
                - error:
                    - unauthorized
                    - forbidden
                  request:
                    header:
                      accept:
                        - text/html
          json:
            enabled: true
            config:
              verbose: true
      authenticators:
        anonymous:
          enabled: true
          config:
            subject: guest
        cookie_session:
          enabled: true
          config:
            check_session_url: http://kratos:4433/sessions/whoami
            preserve_path: true
            extra_from: "@this"
            subject_from: "identity.id"
            only:
              - ory_kratos_session
        noop:
          enabled: true
      authorizers:
        allow:
          enabled: true
      mutators:
        noop:
          enabled: true
        id_token:
          enabled: false
        header:
          enabled: true
          config:
            headers:
              X-Api-User-Id: "{{ print .Extra.identity.id }}"
    

kubeview:
  ingress:
    enabled: true