pgadmin4:
  ingress:
    enabled: true
    hosts:
      - host: localhost
        paths:
        - pathType: Prefix
          path: "/"

postgresql:
  postgresqlPassword: postgres
  postgresqlDatabase: noxudb
  primary:
    priorityClassName: db

kratos:
  kratos:
    autoMigrate: true
    development: true
    ingress:
      public:
        enabled: true
      admin:
        enabled: true
    config:
      dsn: postgres://postgres:postgres@noxucloud-postgresql:5432/noxudb?sslmode=disable&max_conns=20&max_idle_conns=4
      secrets:
        session:
          - dolore occaecat nostrud Ut
          - sit et commodoaute ut voluptate consectetur Duis

oathkeeper:
  oathkeeper:
    config:
      log:
        level: warning
        format: json
      serve:
        proxy:
          cors:
            enabled: true
            allowed_origins:
              - "http://127.0.0.1:4200"
              - "https://*.noxunote.fr"
            allowed_methods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
            allowed_headers:
              - Authorization
              - Content-Type
            exposed_headers:
              - Content-Type
            allow_credentials: true
            debug: true
      errors:
        fallback:
          - json
        handlers:
          redirect:
            enabled: true
            config:
              when:
                - error:
                    - unauthorized
                    - forbidden
                  request:
                    header:
                      accept:
                        - text/html
          json:
            enabled: true
            config:
              verbose: true
      authenticators:
        anonymous:
          enabled: true
          config:
            subject: guest
        cookie_session:
          enabled: true
          config:
            check_session_url: http://kratos:4433/sessions/whoami
            preserve_path: true
            extra_from: "@this"
            subject_from: "identity.id"
            only:
              - ory_kratos_session
        noop:
          enabled: true
      authorizers:
        allow:
          enabled: true
      mutators:
        noop:
          enabled: true
        id_token:
          enabled: true
          config:
            jwks_url: file:///etc/config/oathkeeper/id_token.jwks.json
            claims: |
              {
                "session": {{ .Extra | toJson }}
              }
        header:
          enabled: true
          config:
            headers:
              X-Api-User-Id: "{{ print .Extra.identity.id }}"
    

kubeview:
  ingress:
    enabled: true